name: Docker Build and Push

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-push.yml'

env:
  REGISTRY: harbor.changju.dev
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: |
          echo "HARBOR_ROBOT_USERNAME is set: ${{ secrets.HARBOR_ROBOT_USERNAME != '' }}"
          echo "HARBOR_ROBOT_TOKEN is set: ${{ secrets.HARBOR_ROBOT_TOKEN != '' }}"

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_ROBOT_USERNAME }}
          password: ${{ secrets.HARBOR_ROBOT_TOKEN }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }} 
